export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';

export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';


export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';